### ISSUE TITLE
Service is not restarted delayed

### ISSUE THREAD

**Issue by kri5** [NorthPage/telegraf-cookbook#20] opened 2016-03-03 18:28 UTC
I'm trying to use the cookbook to install telegraf 0.10, and i use the default recipe, plus some telegraf_inputs and telegraf_outputs resource, and even if in the code the notifies are marked as :delayed, it restarts the service immediatly.

I'm not sure what's happening there, but it might be because each time the service is redefined in the resource.

It leads to failure on debian 8.2 where the service is restarted too often too quickly and systemd prevents it from restarting.

Any ideas on how to fix it?

**Comment by tenyo** [comment] 2016-03-04 05:09
@kri5 I think I was able to reproduce this - at least I see that if I define 2 inputs and they both change they restart telegraf twice immediately - although that didn't cause any problems in my case (on Ubuntu 15.04).

As you suspected the problem is that each resource defines its own service so it gets restarted as soon as that resource completes. Unfortunately, the service needs to be defined there in order to be accessible by the restart notification within that resource.

However, to work around this you can use the reload property to disable the automatic restart and handle it yourself.

For example, in your recipe, first define a telegraf service:

```
service "telegraf" do
  service_name 'telegraf'
  action :nothing
end
```

Then create your inputs/outputs like this:

```
telegraf_inputs 'nginx1' do
  inputs node['telegraf']['nginx1']
  reload false
  notifies :restart, "service[telegraf]", :delayed
end

telegraf_inputs 'nginx2' do
  inputs node['telegraf']['nginx2']
  reload false
  notifies :restart, "service[telegraf]", :delayed
end
```

This way telegraf should only get restarted once at the end of your chef run.
Hope that helps!

**Comment by kri5** [comment] 2016-03-07 14:08
Yes that the way i did to make it work, but it looks more like a workaround than the behaviour it should have.

**Comment by fishnix** [comment] 2016-05-07 14:55
I think this is resolved with the referenced PRs.  Let us know if you still have issues.  Thanks!

**Closed as completed by fishnix** 2016-05-07 14:55 UTC
